recipe: default.v1

assistant_id: 20241127-194350-nearest-cymbal

language: "sw"
pipeline:
- name: "WhitespaceTokenizer"
- name: "LanguageModelFeaturizer"
  model_name: "bert"      # Multilingual model that includes Swahili
  model_weights: "bert-base-multilingual-cased"
- name: "DIETClassifier"
  epochs: 100
  constrain_similarities: true
  entity_recognition: true



policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
